[project]
name = "mcp-sandbox"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp[cli]",
    "langchain",
    "langgraph",
    "langchain-mcp-adapters",
    "langchain-google-genai",
    "langchain-openai~=0.2.14"
]
